name: Pull Request CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      id: build
      run: |
        echo 'org.gradle.jvmargs=-Xmx3072m' >> gradle.properties
        ./gradlew :app:assembleDebug
        echo "::set-output name=status::success"
 